app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy="dynamic")
    comments = db.relationship('Comment',backref = 'user',lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)
        
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    title =  db.Column(db.String(255)) 
    pitch_content = db.Column(db.String(255))
    author = db.Column(db.String(255))
    category = db.Column(db.String(255))
    upvote = db.Column(db.Integer)
    downvote = db.Column(db.Integer)
    published_at = db.Column(db.DateTime, default = datetime.utcnow)    
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment',backref = 'pitch',lazy="dynamic")
    

    def __repr__(self):
        return f'User {self.description}'

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    body = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))
            
    published_at = db.Column(db.DateTime, default = datetime.utcnow)  

    def __repr__(self):
        return f'User {self.description}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, RadioField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField('Pitch Title', validators=[Required()])
    author = StringField('Author', validators=[Required()])
    pitch_content = TextAreaField('Write Pitch', validators=[Required()])  
    category = RadioField('Pick Category', choices=[('Pickup Lines', 'Pickup Lines'), ('Interview Pitch', 'Interview Pitch'), ('Product Pitch', 'Product Pitch'), ('Promotion Pitch', 'Promotion Pitch')], validators=[Required()])  
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Say something about yourself...', validators = [Required()])
    submit = SubmitField('Submit')

class CommentsForm(FlaskForm):
    body = TextAreaField('Write a comment...', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)


    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    mail.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # setting config
    # from .requests import configure_request
    # configure_request(app)
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import error,views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Pitch, Comment
from .forms import PitchForm, UpdateProfile, CommentsForm
from flask_login import login_required, current_user
from .. import db, photos

@main.route('/')
@login_required
def index():
    """
    View root page function that returns the index page and its data
    """
    title = 'Pitches'
    product_pitch = Pitch.query.filter_by(category = 'Product Pitch').all()
    pickup_lines = Pitch.query.filter_by(category = 'Pickup Lines').all()
    interview_pitch = Pitch.query.filter_by(category = 'Interview Pitch').all()
    promotion_pitch = Pitch.query.filter_by(category = 'Promotion Pitch').all()

    return render_template('index.html', title = title,product_pitch = product_pitch, pickup_lines = pickup_lines, interview_pitch = interview_pitch, promotion_pitch = promotion_pitch)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template('profile/profile.html', user = user)

@main.route('/user/<uname>/update', methods = ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname = user.username))

    return render_template('profile/update.html', form = form)

@main.route('/user/<uname>/update/pic', methods = ['POST'])
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()

    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile', uname = uname))

@main.route('/pitch/new_pitch', methods = ['GET','POST'])
@login_required
def new_pitch():
    pitch_form = PitchForm()    

    if pitch_form.validate_on_submit():
        pitch = Pitch(title = pitch_form.title.data, category = pitch_form.category.data, pitch_content = pitch_form.pitch_content.data, author = pitch_form.author.data)

        db.session.add(pitch)
        db.session.commit() 
        
        return redirect(url_for('main.index'))
    
    return render_template('new_pitch.html', pitch_form = pitch_form)   

@main.route('/pitch/comments', methods = ['GET', 'POST'])
@login_required
def comments():    
    comments_form = CommentsForm() 
    comments = Comment.query.all()    

    if comments_form.validate_on_submit():       

        # Updated comment instance
        new_comment = Comment(body = comments_form.body.data)

        # Save review method
        new_comment.save_comment()

        return redirect(url_for('main.comments'))
    
    return render_template('comments.html', comments_form = comments_form, comments = comments)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
    
        <title> Welcome to The best Pitching Website  </title>
    
        {% endif %} 
        {% extends 'bootstrap/base.html'%}

        <!-- Navbar block  --> 
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/comments.html
{% extends 'base.html' %} 
{% import 'bootstrap/wtf.html' as wtf %} 
{% import 'macros.html' as macro %} 
{% block content  %}

<div class="container-fluid">
    <div class="row">

        <div class="col-md-4 col-sm-4 col-xs-4" id="column_one">
            <div class="container" style = "background-color: teal; padding: 5%; margin-left: 3%; color: black;">
                {{wtf.quick_form(comments_form)}}
            </div>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-6" id="column_two">
            {{macro.displayCommentsList(comments)}}
        </div>

    </div>
</div>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>WHOOOPS we can't find that page</h1>  
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content %}
<div class ="text" style="background-color:wheat">
<h1 style="color:teal; background-color:wheat;text-align:center;">Welcome to The Pitching Website</h1>


<ul style = "text-align: left ; font-size :24px">
  <li>
    <a class="nav-link" data-toggle="tab" href="#Products" role="tab">Products</a>
  </li>
  <li >
    <a class="nav-link" data-toggle="tab" href="#Pickups" role="tab">Pickup Lines</a>
  </li>
  <li >
    <a class="nav-link" data-toggle="tab" href="#Interviews" role="tab">Interviews</a>
  </li>
  <li >
    <a class="nav-link" data-toggle="tab" href="#Promotions" role="tab">Promotions</a>
  </li>
</ul>

<a href="{{url_for('main.new_pitch')}}" style = "margin-left: 20.25%; color: blue;font-size: 16px">
  <span >Create new Pitch<span>
</a>
</div>

<div class="tab-content" style="background-color:teal;color:white">
  <div style="margin-top: 1em;" class="tab-pane" id="Products" role="tabpanel">
    <div class="container-fluid" style="margin: 0% 2%">
      <div class="row">
        {{macro.displayPitchList(product_pitch)}}
      </div>
    </div>
  </div>
  <div style="margin-top: 1em;" class="tab-pane" id="Pickups" role="tabpanel">
    <div class="container-fluid" style="margin: 0% 2%">
      <div class="row">
        {{macro.displayPitchList(pickup_lines)}}
      </div>
    </div>
  </div>
  <div style="margin-top: 1em;" class="tab-pane" id="Interviews" role="tabpanel">
    <div class="container-fluid" style="margin: 0% 2%">
      <div class="row">
        {{macro.displayPitchList(interview_pitch)}}
      </div>
    </div>
  </div>
  <div style="margin-top: 1em;" class="tab-pane" id="Promotions" role="tabpanel">
    <div class="container-fluid" style="margin: 0% 2%">
      <div class="row">
        {{macro.displayPitchList(promotion_pitch)}}
      </div>
    </div>
  </div>
</div>
{% endblock%}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %} {% for pitch in pitch_list %}


<div class="col-md-3 col-sm-6 col-xs-6" id='pitch'>
    <div class="card">
        <div class="card-header" style="color: white
        ;">
            <b>{{pitch.category}}</b>
        </div>
        <div class="card-body">
            <h5 class="card-title" style="color: rgba(0, 0, 0, 0.7);">{{pitch.title}}</h5>
            <p class="card-text" style="color: rgb(73, 72, 72);">
                <i>{{pitch.pitch_content}}</i>
            </p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="font-size: 14px; color: dodgerblue;">~ {{pitch.author}}
                <a href="">
                    <span class="fas fa-thumbs-up"></span>
                </a>&ensp;
                <a href="">
                    <span class="fas fa-thumbs-down"></span>
                </a>&ensp;
                <a href="{{url_for('main.comments')}}">
                    <span class="fas fa-comments"></span>
                </a>
            </li>
            <li class="list-group-item">{{pitch.published_at}}</li>
            <li class="list-group-item" style="background-color: whitesmoke;">
                <a href="{{url_for('main.new_pitch')}}" class="new_pitch">
                    <span id="new_pitch">Click to create a new Pitch
                        <span>
                </a>
            </li>
        </ul>
    </div>
</div>

{% endfor %} {% endmacro %} 

{% macro displayCommentsList(comments_list) %} {% for comment in comments_list %}

<div class="container">

    {{comment.description}}

</div><br>

<style>
    .container {
        background-color: #0e91a6; 
        padding: 3.5% 5%; 
        margin-left: 3%;
        border-radius: 10px;
        color: whitesmoke;
    }
</style>

{% endfor %} 
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Pitches</a>

  <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated and current_user.profile_pic_path is none %}
      <!-- <span class="nav-item" style="height: 42.97px; width: 50.97px;"><a href="{{url_for('main.profile',uname=current_user.username)}}"><img src="{{url_for('static', filename = 'imgs/avatar.png')}}" alt="" style="height: 42.97px; width: 42.97px; border-radius: 50%; border-right: 2.5px solid white; border-bottom: 2.5px solid white"></a></span>  -->
      <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a>
          </li>        
          <li class="nav-item">
              <a class="nav-link" href="{{url_for('auth.logout')}}">Signout</a>
          </li>  

      {% elif current_user.is_authenticated and current_user.profile_pic_path %}
      <span class="nav-item" style="height: 42.97px; width: 50.97px;"><a href="{{url_for('main.profile',uname=current_user.username)}}"><img src="{{url_for('static', filename = current_user.profile_pic_path)}}" alt="" style="height: 42.97px; width: 42.97px; border-radius: 50%; border-right: 2.5px solid white; border-bottom: 2.5px solid white"></a></span>
      <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a>
      </li>        
      <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}">Signout</a>
      </li>      

      {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Signin</a>
      </li>
      {% endif %}
  </ul>
</nav>

app/templates/new_pitch.html
{% extends 'base.html' %} 

{% import 'bootstrap/wtf.html' as wtf %}

{% block body %}
<div class="container-fluid" style="background-color:wheat">

    <div class="container">
  
      {{wtf.quick_form(pitch_form)}}
  
    </div>
  </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} joined Pitches </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}